"use client";

import { FormEvent, PointerEvent as ReactPointerEvent, useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { jobCompletionTerms } from "../../lib/job-completion-data";
import { quoteFormEndpoint, web3FormsAccessKey } from "../../lib/site-data";

type FormState = {
  customerName: string; phone: string; email: string; jobReference: string; pickupAddress: string; deliveryAddress: string;
  jobDate: string; crew: string; startTime: string; finishTime: string; chargedTime: string; serviceCharge: string;
  additionalCharges: string; depositPaid: string; paymentMethod: string; comments: string; signedBy: string;
};
type Errors = Partial<Record<keyof FormState | "readTerms" | "agreeTerms" | "jobCompleted" | "signature", string>>;
const initialForm: FormState = { customerName: "", phone: "", email: "", jobReference: "", pickupAddress: "", deliveryAddress: "", jobDate: "", crew: "", startTime: "", finishTime: "", chargedTime: "", serviceCharge: "", additionalCharges: "", depositPaid: "", paymentMethod: "", comments: "", signedBy: "" };
const currency = new Intl.NumberFormat("en-AU", { style: "currency", currency: "AUD" });
const asAmount = (value: string) => { const amount = Number(value); return Number.isFinite(amount) && amount >= 0 ? amount : 0; };
const formatTime = (iso: string) => new Intl.DateTimeFormat("en-AU", { timeZone: "Australia/Adelaide", dateStyle: "short", timeStyle: "short" }).format(new Date(iso));

function Field({ label, name, required, type = "text", value, onChange, error, autoComplete, step, min, children }: { label: string; name: keyof FormState; required?: boolean; type?: string; value: string; onChange: (value: string) => void; error?: string; autoComplete?: string; step?: string; min?: string; children?: React.ReactNode }) {
  const id = `job-${name}`;
  return <label className="job-field" htmlFor={id}><span>{label}{required && <b aria-hidden="true"> *</b>}</span>{children ?? <input id={id} name={name} type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} autoComplete={autoComplete} step={step} min={min} aria-invalid={Boolean(error)} aria-describedby={error ? `${id}-error` : undefined} />}{error && <small id={`${id}-error`} className="job-error">{error}</small>}</label>;
}

function SignaturePad({ value, onChange, error }: { value: string; onChange: (value: string) => void; error?: string }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const drawing = useRef(false);
  const lastPoint = useRef<{ x: number; y: number } | null>(null);
  const inkRef = useRef(Boolean(value));
  const [hasInk, setHasInk] = useState(Boolean(value));

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const resize = () => {
      const old = canvas.toDataURL();
      const rect = canvas.getBoundingClientRect();
      const ratio = Math.max(1, Math.min(2, window.devicePixelRatio || 1));
      canvas.width = Math.round(rect.width * ratio); canvas.height = Math.round(rect.height * ratio);
      const context = canvas.getContext("2d");
      if (!context) return;
      context.scale(ratio, ratio); context.lineCap = "round"; context.lineJoin = "round"; context.lineWidth = 2.2; context.strokeStyle = "#f9f7f0";
      if (inkRef.current) { const image = new Image(); image.onload = () => context.drawImage(image, 0, 0, rect.width, rect.height); image.src = old; }
    };
    resize(); window.addEventListener("resize", resize); return () => window.removeEventListener("resize", resize);
  }, []);

  const point = (event: ReactPointerEvent<HTMLCanvasElement>) => { const rect = event.currentTarget.getBoundingClientRect(); return { x: event.clientX - rect.left, y: event.clientY - rect.top }; };
  const start = (event: ReactPointerEvent<HTMLCanvasElement>) => { event.preventDefault(); event.currentTarget.setPointerCapture(event.pointerId); drawing.current = true; lastPoint.current = point(event); };
  const move = (event: ReactPointerEvent<HTMLCanvasElement>) => { if (!drawing.current || !lastPoint.current) return; event.preventDefault(); const next = point(event); const context = canvasRef.current?.getContext("2d"); if (!context) return; context.beginPath(); context.moveTo(lastPoint.current.x, lastPoint.current.y); context.lineTo(next.x, next.y); context.stroke(); lastPoint.current = next; inkRef.current = true; setHasInk(true); };
  const end = () => { if (!drawing.current) return; drawing.current = false; lastPoint.current = null; const data = canvasRef.current?.toDataURL("image/png"); if (data) onChange(data); };
  const clear = () => { const canvas = canvasRef.current; const context = canvas?.getContext("2d"); if (canvas && context) context.clearRect(0, 0, canvas.width, canvas.height); inkRef.current = false; setHasInk(false); onChange(""); };
  return <div className="signature-field"><div className="job-field-heading"><span id="signature-label">Customer Signature <b aria-hidden="true">*</b></span><button type="button" className="job-clear" onClick={clear} disabled={!hasInk}>Clear</button></div><p id="signature-help" className="job-help">Use your finger, stylus or mouse to sign in the box below.</p><canvas ref={canvasRef} className="signature-canvas" aria-labelledby="signature-label" aria-describedby="signature-help" onPointerDown={start} onPointerMove={move} onPointerUp={end} onPointerCancel={end} onPointerLeave={end} />{error && <small className="job-error">{error}</small>}</div>;
}

export function JobCompletionForm() {
  const pathname = usePathname();
  const [form, setForm] = useState(initialForm); const [signature, setSignature] = useState(""); const [checks, setChecks] = useState({ readTerms: false, agreeTerms: false, jobCompleted: false });
  const [completionIso, setCompletionIso] = useState(""); const [errors, setErrors] = useState<Errors>({}); const [status, setStatus] = useState(""); const [statusKind, setStatusKind] = useState<"success" | "error" | "info">("info"); const [loading, setLoading] = useState(false); const [submitted, setSubmitted] = useState(false); const formRef = useRef<HTMLFormElement>(null); const submitting = useRef(false);
  const total = asAmount(form.serviceCharge) + asAmount(form.additionalCharges); const balance = Math.max(0, total - asAmount(form.depositPaid)); const remaining = 3000 - form.comments.length;
  const update = (name: keyof FormState, value: string) => setForm((current) => ({ ...current, [name]: value }));
  const signatureChanged = (value: string) => { setSignature(value); if (value && !completionIso) setCompletionIso(new Date().toISOString()); };
  const validate = () => { const next: Errors = {}; const required: Array<[keyof FormState, string]> = [["customerName", "Enter the customer name."], ["phone", "Enter a mobile number."], ["pickupAddress", "Enter the pick-up address."], ["deliveryAddress", "Enter the delivery address."], ["jobDate", "Select the job date."], ["startTime", "Enter the start time."], ["finishTime", "Enter the finish time."], ["signedBy", "Enter the name of the person signing."]]; required.forEach(([name, message]) => { if (!form[name].trim()) next[name] = message; }); if (form.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) next.email = "Enter a valid email address or leave this blank."; (["serviceCharge", "additionalCharges", "depositPaid"] as const).forEach((name) => { if (form[name] && (Number(form[name]) < 0 || !Number.isFinite(Number(form[name])))) next[name] = "Enter a zero or positive amount."; }); if (!checks.readTerms) next.readTerms = "Read the terms before continuing."; if (!checks.agreeTerms) next.agreeTerms = "Agree to the terms before continuing."; if (!checks.jobCompleted) next.jobCompleted = "Confirm the service is complete."; if (!signature) next.signature = "Add the customer signature before submitting."; setErrors(next); return next; };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (submitting.current || submitted) return; const next = validate(); if (Object.keys(next).length) { setStatusKind("error"); setStatus("Please complete the highlighted fields before submitting."); const first = Object.keys(next)[0]; formRef.current?.querySelector<HTMLElement>(`[name="${first}"]`)?.focus(); return; } const iso = completionIso || new Date().toISOString(); setCompletionIso(iso); submitting.current = true; setLoading(true); setStatusKind("info"); setStatus("Submitting…"); try { const data = new FormData(); const values: Record<string, string> = { access_key: web3FormsAccessKey, subject: "HF Removals Adelaide - Job Completion Form", from_name: "HF Removals Adelaide Website", form_type: "Job Completion Form", customer_name: form.customerName, phone: form.phone, email: form.email, job_reference: form.jobReference, pickup_address: form.pickupAddress, delivery_address: form.deliveryAddress, job_date: form.jobDate, crew: form.crew, start_time: form.startTime, finish_time: form.finishTime, charged_time: form.chargedTime, service_charge: currency.format(asAmount(form.serviceCharge)), additional_charges: currency.format(asAmount(form.additionalCharges)), deposit_paid: currency.format(asAmount(form.depositPaid)), payment_method: form.paymentMethod, calculated_total: currency.format(total), calculated_balance_due: currency.format(balance), read_terms: String(checks.readTerms), agree_terms: String(checks.agreeTerms), job_completed: String(checks.jobCompleted), comments: form.comments, signed_by: form.signedBy, completion_timestamp: iso, page_url: `${window.location.origin}${pathname}`, signature }; Object.entries(values).forEach(([key, value]) => data.append(key, value)); const response = await fetch(quoteFormEndpoint, { method: "POST", body: data }); const result: { success?: boolean; message?: string } = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || "Submission failed"); setSubmitted(true); setStatusKind("success"); setStatus("Job completion form submitted successfully."); } catch { setStatusKind("error"); setStatus("The form could not be submitted. Please check the connection and try again."); } finally { submitting.current = false; setLoading(false); } }
  return <form ref={formRef} className="job-completion-form" onSubmit={submit} noValidate onInvalid={() => setStatus("Please complete the highlighted fields before submitting.")}>
    <section className="job-form-card"><div className="job-section-heading"><span className="job-section-number">01</span><div><p className="eyebrow">The move record</p><h2>Customer &amp; job details</h2></div></div><div className="job-form-grid"><Field label="Customer Name" name="customerName" required value={form.customerName} onChange={(value) => update("customerName", value)} error={errors.customerName} autoComplete="name" /><Field label="Mobile Number" name="phone" required type="tel" value={form.phone} onChange={(value) => update("phone", value)} error={errors.phone} autoComplete="tel" /><Field label="Email" name="email" type="email" value={form.email} onChange={(value) => update("email", value)} error={errors.email} autoComplete="email" /><Field label="Job / Booking Reference" name="jobReference" value={form.jobReference} onChange={(value) => update("jobReference", value)} /><Field label="Pick-up Address" name="pickupAddress" required value={form.pickupAddress} onChange={(value) => update("pickupAddress", value)} error={errors.pickupAddress} autoComplete="street-address" /><Field label="Delivery Address" name="deliveryAddress" required value={form.deliveryAddress} onChange={(value) => update("deliveryAddress", value)} error={errors.deliveryAddress} autoComplete="street-address" /><Field label="Job Date" name="jobDate" required type="date" value={form.jobDate} onChange={(value) => update("jobDate", value)} error={errors.jobDate} /><Field label="Crew / Removalists" name="crew" value={form.crew} onChange={(value) => update("crew", value)} /></div></section>
    <section className="job-form-card"><div className="job-section-heading"><span className="job-section-number">02</span><div><p className="eyebrow">Close-out figures</p><h2>Time &amp; payment summary</h2></div></div><div className="job-form-grid"><Field label="Start Time" name="startTime" required type="time" value={form.startTime} onChange={(value) => update("startTime", value)} error={errors.startTime} /><Field label="Finish Time" name="finishTime" required type="time" value={form.finishTime} onChange={(value) => update("finishTime", value)} error={errors.finishTime} /><Field label="Charged Time / Hours" name="chargedTime" value={form.chargedTime} onChange={(value) => update("chargedTime", value)} /><Field label="Service Charge" name="serviceCharge" type="number" value={form.serviceCharge} onChange={(value) => update("serviceCharge", value)} error={errors.serviceCharge} min="0" step="0.01" /><Field label="Additional Charges" name="additionalCharges" type="number" value={form.additionalCharges} onChange={(value) => update("additionalCharges", value)} error={errors.additionalCharges} min="0" step="0.01" /><Field label="Deposit Already Paid" name="depositPaid" type="number" value={form.depositPaid} onChange={(value) => update("depositPaid", value)} error={errors.depositPaid} min="0" step="0.01" /><Field label="Payment Method" name="paymentMethod" value={form.paymentMethod} onChange={(value) => update("paymentMethod", value)}>{<select id="job-paymentMethod" name="paymentMethod" value={form.paymentMethod} onChange={(event) => update("paymentMethod", event.target.value)}><option value="">Select method</option><option>Card</option><option>Bank Transfer</option><option>Cash</option><option>Other</option></select>}</Field></div><div className="job-totals" aria-live="polite"><div><span>Total Job Amount</span><strong>{currency.format(total)}</strong></div><div><span>Balance Due</span><strong>{currency.format(balance)}</strong></div></div></section>
    <section className="job-form-card terms-card"><div className="job-section-heading"><span className="job-section-number">03</span><div><p className="eyebrow">Please read carefully</p><h2>Terms &amp; conditions</h2></div></div><div className="terms-panel"><ol>{jobCompletionTerms.map((term, index) => <li key={index}>{term}</li>)}</ol></div><div className="job-checks">{([["readTerms", "I have read and fully understand the contents of this document."], ["agreeTerms", "I agree to the terms and conditions stated above."], ["jobCompleted", "I confirm the moving service has been completed."]] as const).map(([name, label]) => <label className="job-check" key={name}><input type="checkbox" name={name} checked={checks[name]} onChange={(event) => setChecks((current) => ({ ...current, [name]: event.target.checked }))} /><span>{label}</span></label>)}{(errors.readTerms || errors.agreeTerms || errors.jobCompleted) && <small className="job-error">{errors.readTerms || errors.agreeTerms || errors.jobCompleted}</small>}</div></section>
    <section className="job-form-card"><div className="job-section-heading"><span className="job-section-number">04</span><div><p className="eyebrow">Final acknowledgement</p><h2>Comments &amp; signature</h2></div></div><label className="job-field" htmlFor="job-comments"><span>Comments</span><textarea id="job-comments" name="comments" maxLength={3000} value={form.comments} onChange={(event) => update("comments", event.target.value)} placeholder="Add any comments about the completed move, damage noted before departure, payment notes, or other relevant information." /><small className="job-counter">{remaining} characters remaining</small></label><div className="job-signature-grid"><SignaturePad value={signature} onChange={signatureChanged} error={errors.signature} /><div className="job-signing-details"><Field label="Signed By" name="signedBy" required value={form.signedBy} onChange={(value) => update("signedBy", value)} error={errors.signedBy} autoComplete="name" /><div className="job-field"><span>Completion Time</span><output className="job-output">{completionIso ? formatTime(completionIso) : "Populates when signed"}</output><small className="job-help">The exact completion timestamp is recorded with the submission.</small></div></div></div></section>
    <div className="job-actions"><div className={`job-status ${statusKind}`} role="status" aria-live="polite">{status}</div><div className="job-action-buttons"><button type="button" className="button button-outline" onClick={() => window.print()}>Print / Save PDF</button><button type="submit" className="button button-ruby" disabled={loading || submitted}>{loading ? "Submitting…" : submitted ? "Submission confirmed" : "Submit completion form"}</button></div></div>
    {submitted && <div className="job-success" role="status"><p className="eyebrow">Submission confirmed</p><h2>Thank you, {form.customerName}.</h2><p>{form.jobReference ? `Job reference ${form.jobReference}. ` : ""}Completed {completionIso ? formatTime(completionIso) : "today"}. You can print or save a copy above.</p></div>}
  </form>;
}
